name: Window
options:
  bundleIdPrefix: com.window
  deploymentTarget:
    iOS: "17.0"

targets:
  Window:
    type: application
    platform: iOS
    sources:
      - path: Window
        includes:
          - "**/*.swift"
        excludes:
          - "**/*.md"
      - path: Window/Assets.xcassets
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.window.app
        PRODUCT_NAME: Window
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: Window/Info.plist
      properties:
        CFBundleDisplayName: Window
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  Window:
    build:
      targets:
        Window: all
    run:
      config: Debug
